name: 部署文档

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # 如果你文档需要 Git 子模块，取消注释下一行
          # submodules: true

      - name: 设置 pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10


      - name: 设置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: 安装依赖
        run: |
          corepack enable
          pnpm install --frozen-lockfile

      - name: 创建docs目录和禁用Jekyll
        run: |
          mkdir -p docs
          touch docs/.nojekyll
          touch .nojekyll

      - name: 构建文档
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: |-
          pnpm run docs:build
          touch src/.vuepress/dist/.nojekyll

      - name: 调试信息
        run: |
          echo "列出构建目录内容"
          ls -la src/.vuepress/dist/
          echo "列出资源目录内容"
          ls -la src/.vuepress/dist/assets/ || echo "资源目录不存在"

      - name: 部署文档
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          # 部署文档
          branch: gh-pages
          folder: src/.vuepress/dist
          token: ${{ secrets.GITHUB_TOKEN }}
          clean: true
          clean-exclude: |
            .nojekyll
